services:
  app:
    build:
      context: ./infra/docker/php
      #app
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  web:
    image: nginx:1.29.0-alpine # 公式イメージを指定
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html/public:ro
      - ./infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0 # 公式イメージを指定
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #password
      MYSQL_DATABASE: ${DB_DATABASE}
      #laravel_db
      MYSQL_USER: ${DB_USERNAME}       
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # ブラウザからは http://localhost:8081 でアクセス
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db    

volumes:
  db-data: